# Generated by Django 6.0.7 on 2026-09-02 02:59

import django.db.models.deletion
import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('content', django_editorjs_fields.fields.EditorJsJSONField(verbose_name='Содержимое')),
                ('show_in_navigation', models.BooleanField(default=True, verbose_name='Показывать в навигации')),
                ('navigation_order', models.PositiveIntegerField(default=0, verbose_name='Порядок в навигации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='website.page', verbose_name='Родительский раздел')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['navigation_order', 'title'],
            },
        ),
    ]
