# Generated by Django 6.0.7 on 2026-09-02 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать в меню')),
            ],
            options={
                'verbose_name': 'Раздел меню',
                'verbose_name_plural': 'Разделы меню',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='page',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='page',
            name='show_in_navigation',
        ),
        migrations.AlterField(
            model_name='page',
            name='navigation_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в разделе'),
        ),
        migrations.AddField(
            model_name='page',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='website.navigationsection', verbose_name='Раздел меню'),
        ),
    ]
