# Generated by Django 6.0.7 on 2026-07-24 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0002_doctor_doctorschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('consultation', 'Консультации специалистов'), ('analysis', 'Анализы'), ('diagnostic', 'Диагностика'), ('procedure', 'Процедуры'), ('dentistry', 'Стоматология'), ('rehabilitation', 'Реабилитация')], max_length=50, verbose_name='Категория')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Длительность (минуты)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mis.medicalservice', verbose_name='Родительская услуга')),
            ],
        ),
    ]
