# Generated by Django 6.0.7 on 2026-07-24 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0003_medicalservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalservice',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Справочник услуг'},
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mis.medicalservice', verbose_name='Родительская услуга'),
        ),
    ]
