# Generated by Django 6.0.7 on 2026-07-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0004_alter_medicalservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='mis.medicalservice', verbose_name='Оказываемые услуги'),
        ),
    ]
