# Generated by Django 6.0.7 on 2026-07-24 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0005_doctor_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('is_available', models.BooleanField(default=True, verbose_name='Свободен')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.doctor', verbose_name='Врач')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.medicalservice', verbose_name='Услуга')),
            ],
        ),
    ]
