# Generated by Django 6.0.7 on 2026-07-24 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0006_appointmentslot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentslot',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='mis.doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='mis.medicalservice', verbose_name='Услуга'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('no_show', 'Не явился')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.patient')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mis.appointmentslot')),
            ],
        ),
    ]
