# Generated by Django 6.0.7 on 2026-08-23 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0007_alter_appointmentslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='personal_data_consent_signed',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПД подписано очно'),
        ),
        migrations.AddField(
            model_name='patient',
            name='personal_data_consent_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания согласия'),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('analysis', 'Анализ'), ('research', 'Исследование'), ('visit_protocol', 'Протокол приёма')], max_length=30, verbose_name='Тип записи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('result', models.TextField(blank=True, verbose_name='Результат')),
                ('conclusion', models.TextField(blank=True, verbose_name='Заключение')),
                ('protocol', models.TextField(blank=True, verbose_name='Протокол')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='mis.doctor', verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='mis.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Медицинская запись',
                'verbose_name_plural': 'Медицинские записи',
                'ordering': ['-date'],
            },
        ),
    ]
