# Generated by Django 6.0.7 on 2026-08-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0008_patient_personal_data_consent_signed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
    ]
