# Generated by Django 6.0.7 on 2026-08-23 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0009_medicalrecord_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={},
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='title',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='mis.medicalservice', verbose_name='Услуга'),
            preserve_default=False,
        ),
    ]
