# Generated by Django 6.0.7 on 2026-08-25 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0010_alter_medicalrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='mis.appointmentslot'),
        ),
    ]
